### ISSUE TITLE
佬，脚本挂了

### ISSUE THREAD

**Issue by AinzRimuru** [himcs/LeishenAuto#3]
```
Run node main.js
🌀雷神加速器暂停助手 开始运行-------
(node:1552) UnhandledPromiseRejectionWarning: Error: Request failed with status code 418
    at createError (/home/runner/work/LeishenStop/LeishenStop/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/runner/work/LeishenStop/LeishenStop/node_modules/axios/lib/core/settle.js:1[7](https://github.com/AinzLimuru/LeishenStop/actions/runs/********#step:5:8):12)
    at IncomingMessage.handleStreamEnd (/home/runner/work/LeishenStop/LeishenStop/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:1552) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:1552) [DEP001[8](https://github.com/************#step:5:9)] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Seayon** [comment]
@AinzLimuru 

https://github.com/himcs/LeishenAuto/pull/4 
官网登录接口加签名了，我给他提了个 pr，或者先 fork 我 main 分支的使用 
https://github.com/Seayon/LeishenAuto

**Comment by AinzRimuru** [comment]
> @AinzLimuru
> 
> #4 官网登录接口加签名了，我给他提了个 pr，或者先 fork 我 main 分支的使用 https://github.com/Seayon/LeishenAuto

@Seayon 佬，脚本又挂了，今天刚挂，热乎的，你自己的Action也有相同的日志

**Comment by luanche** [comment]
感觉应该是雷神的api被服务器运营商墙了，雷神自己的官网也没办法用密码登陆了
![image](https://github.com/user-attachments/assets/5f1abea6-e259-46df-99aa-fa64806c75fd)

**Comment by Seayon** [comment]
![image](https://github.com/user-attachments/assets/0b0cc18f-f927-41f7-9e78-2db958c6c2d5)

没错啊，官网自己都坏了

**Comment by luanche** [comment]
现在又正常了，我的已经可以用了

**Comment by luanche** [comment]
官网的登陆接口又没办法用了，可以试试改成移动端网站的登陆接口，我刚试了能用。拿到token之后其他接口可以不用变
https://www.leigod.com/m/mlogin.html?region_code=1&language=en&platform=0
`https://webapi.leigod.com/wap/login/bind/v1`
```json
{
  "username": "",
  "password": "",
  "user_type": "0",
  "src_channel": "guanwang",
  "code": "",
  "country_code": 86,
  "lang": "en",
  "os_type": 5,
  "ts": "1733277420",
  "sign": ""
}
```

**Comment by tttwwy** [comment]
又不能使用了，是否方便更新一下，非常感谢

**Comment by Seayon** [comment]
> 又不能使用了，是否方便更新一下，非常感谢

@tttwwy 

官网登录接口增加了验证码，登录的路子不好走。
我切换成了手动登录拿 account_token 然后直接配置 account_token 的方法，不过没有验证 account_token 可以使用多久，在分支
https://github.com/Seayon/LeishenAuto/tree/feature/switch-wap-login  你可以合并尝试一下
等我验证好后会提交 pr。

**Comment by tttwwy** [comment]
> > 又不能使用了，是否方便更新一下，非常感谢
> 
> [@tttwwy](https://github.com/tttwwy)
> 
> 官网登录接口增加了验证码，登录的路子不好走。 我切换成了手动登录拿 account_token 然后直接配置 account_token 的方法，不过没有验证 account_token 可以使用多久，在分支 https://github.com/Seayon/LeishenAuto/tree/feature/switch-wap-login 你可以合并尝试一下 等我验证好后会提交 pr。

非常感谢，我试一下看看
